Repository skycoin/skywire, pull requests merged in 2019-05, with the labels that each got.

#325 Fix panic on confirm loop.
  pkg/router/routingtablemanager.go
Labels: bug, mainnet

#341 Ensure that log files are closed after opening.
  pkg/transport/log.go
Labels: bug, mainnet

#333 Refactored 'router' module to improve testability.
  pkg/node/node.go
  pkg/router/procmanager.go
  pkg/router/procmanager_handlers.go
  pkg/router/router.go
  pkg/router/router_multiplexers.go
Labels: enhancement, mainnet

#351 added retry on sequence error for update
  pkg/messaging-discovery/client/client.go
  pkg/messaging-discovery/client/client_mock_test.go
  pkg/messaging-discovery/client/entry.go
  pkg/messaging-discovery/client/testing.go
Labels: bug, mainnet

#361 Fix messaging data race 354.
  pkg/messaging/channel.go
  pkg/messaging/client.go
  pkg/node/node.go
Labels: bug, mainnet

#373 Fixed faulty test that is discovered after gz-c's PR.
  pkg/messaging/chan_list.go
  pkg/messaging/channel.go
  pkg/messaging/channel_test.go
  pkg/messaging/client.go
  pkg/messaging/client_test.go
Labels: bug
