Repository skycoin/skywire, pull requests merged in 2019-04, with the labels that each got.

#268 fixed ack issue
  internal/ioutil/ack.go
Labels: bug, mainnet

#274 Removed debug messages.
  pkg/router/route_manager.go
  pkg/router/route_manager_test.go
  pkg/setup/protocol.go
Labels: mainnet

#275 [mainnet-manager] Added TCP Addr to Node Summary in Manager Node.
  pkg/manager/node.go
Labels: mainnet

#277 [mainnet-manager] Added Versioning to node summary endpoint.
  cmd/skywire-node/commands/version.go
  pkg/node/node.go
  pkg/node/rpc.go
  pkg/node/rpc_client.go
Labels: mainnet

#284 Detect unstable tests in mainnet branch
  ci_scripts/run-internal-tests.sh
  ci_scripts/run-pkg-tests.sh
  docs/Tests.Detection-of-unstable-tests.md
  internal/noise/read_writer_test.go
  pkg/messaging/client_no_ci_test.go
  pkg/messaging/client_test.go
Labels: mainnet

#252 Deterministic properties of Transports. Linked to "Apps create multiple transports-248"
  Makefile
  cmd/skywire-cli/commands/tpdisc/root.go
  go.mod
  go.sum
  pkg/app/packet.go
  pkg/app/packet_test.go
  pkg/messaging/channel.go
  pkg/messaging/channel_test.go
  pkg/messaging/client.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/rpc.go
  pkg/node/rpc_client.go
  pkg/node/rpc_test.go
  pkg/route-finder/client/mock.go
  pkg/router/route_manager.go
  pkg/router/route_manager_test.go
  pkg/router/router.go
  pkg/router/router_test.go
  pkg/setup/protocol.go
  pkg/setup/protocol_test.go
  pkg/transport-discovery/client/client_test.go
  pkg/transport/discovery.go
  pkg/transport/discovery_test.go
  pkg/transport/entry.go
  pkg/transport/entry_test.go
  pkg/transport/handshake.go
  pkg/transport/handshake_test.go
  pkg/transport/manager.go
  pkg/transport/manager_test.go
  pkg/transport/mock.go
  pkg/transport/tcp_transport.go
  pkg/transport/tcp_transport_test.go
  pkg/transport/transport.go
Labels: mainnet

#291 Remove duplicated tests in pkg/router/router_test.go and internal/therealssh/client_test.go
  Makefile
  internal/therealssh/client_test.go
  pkg/router/router_test.go
Labels: cleanup, mainnet

#294 Enhancement: Ability to send logs to syslog
  Makefile
  cmd/skywire-node/commands/root.go
  go.mod
  pkg/setup/mock_node_test.go
Labels: enhancement, mainnet

#300 reverted json encoding
  pkg/router/route_manager.go
  pkg/routing/loop.go
  pkg/routing/route.go
  pkg/setup/protocol.go
Labels: bug, mainnet

#289 [WIP] removed internal/ack
  cmd/apps/chat/chat.go
  internal/ioutil/ack.go
  internal/ioutil/ack_test.go
  pkg/app/app.go
  pkg/messaging/channel.go
  pkg/messaging/client.go
  pkg/messaging/pool_test.go
Labels: bug, mainnet

#307 Feature/move metrics and httputil into ./pkg/
  cmd/setup-node/commands/root.go
  go.mod
  go.sum
  pkg/httputil/httputil.go
  pkg/manager/node.go
  pkg/manager/user_manager.go
  pkg/metrics/messaging.go
  pkg/metrics/metrics.go
  pkg/setup/node.go
  pkg/setup/node_test.go
  vendor/github.com/gorilla/handlers/.travis.yml
  vendor/github.com/gorilla/handlers/LICENSE
  vendor/github.com/gorilla/handlers/README.md
  vendor/github.com/gorilla/handlers/canonical.go
  vendor/github.com/gorilla/handlers/compress.go
  vendor/github.com/gorilla/handlers/cors.go
  vendor/github.com/gorilla/handlers/doc.go
  vendor/github.com/gorilla/handlers/handlers.go
  vendor/github.com/gorilla/handlers/handlers_go18.go
  vendor/github.com/gorilla/handlers/handlers_pre18.go
  vendor/github.com/gorilla/handlers/logging.go
  vendor/github.com/gorilla/handlers/proxy_headers.go
  vendor/github.com/gorilla/handlers/recovery.go
  vendor/modules.txt
Labels: mainnet

#314 Fix merge conflicts.
  cmd/apps/chat/chat.go
  cmd/setup-node/commands/root.go
  cmd/skywire-node/commands/root.go
  go.mod
  go.sum
  internal/ioutil/ack.go
  internal/ioutil/ack_test.go
  pkg/httputil/httputil.go
  pkg/manager/node.go
  pkg/manager/user_manager.go
  pkg/messaging/channel.go
  pkg/messaging/client.go
  pkg/messaging/pool_test.go
  pkg/metrics/messaging.go
  pkg/metrics/metrics.go
  pkg/routing/loop.go
  pkg/routing/route.go
  pkg/setup/node.go
  pkg/setup/node_test.go
  pkg/setup/protocol.go
  vendor/github.com/gorilla/handlers/.travis.yml
  vendor/github.com/gorilla/handlers/LICENSE
  vendor/github.com/gorilla/handlers/README.md
  vendor/github.com/gorilla/handlers/canonical.go
  vendor/github.com/gorilla/handlers/compress.go
  vendor/github.com/gorilla/handlers/cors.go
  vendor/github.com/gorilla/handlers/doc.go
  vendor/github.com/gorilla/handlers/handlers.go
  vendor/github.com/gorilla/handlers/handlers_go18.go
  vendor/github.com/gorilla/handlers/handlers_pre18.go
  vendor/github.com/gorilla/handlers/logging.go
  vendor/github.com/gorilla/handlers/proxy_headers.go
  vendor/github.com/gorilla/handlers/recovery.go
  vendor/modules.txt
Labels: mainnet
