Repository skycoin/skywire, pull requests merged in 2019-06, with the labels that each got.

#393 Integration scripts for skywire with public services
  Makefile
  integration/InteractiveEnvironments.md
  integration/check-route-finder.sh
  integration/check-services.sh
  integration/generic/env-vars.sh
  integration/generic/nodeA.json
  integration/generic/nodeC.json
  integration/intermediary-nodeB.json
  integration/messaging/env-vars.sh
  integration/messaging/nodeA.json
  integration/messaging/nodeC.json
  integration/proxy/env-vars.sh
  integration/proxy/nodeA.json
  integration/proxy/nodeC.json
  integration/run-generic-env.sh
  integration/run-messaging-env.sh
  integration/run-proxy-env.sh
  integration/run-ssh-env.sh
  integration/ssh/env-vars.sh
  integration/ssh/nodeA.json
  integration/ssh/nodeC.json
  integration/start-restart-nodeB.sh
  integration/startup.sh
  integration/tear-down.sh
  integration/test-messaging-loop.sh
  integration/test-messaging.sh
  integration/test-proxy.sh
  integration/test-ssh.sh
  pkg/messaging/channel.go
  pkg/messaging/factory.go
  pkg/transport/handshake.go
Labels: mainnet

#410 Fixed possible panics of transport re-establishment.
  pkg/transport/manager.go
Labels: bug, mainnet

#416 Logging improvements for running and testing skywire-node
  Makefile
  README.md
  cmd/skywire-node/commands/root.go
  cmd/skywire-node/skywire-node.go
  go.mod
  go.sum
  integration/run-generic-env.sh
  integration/run-messaging-env.sh
  integration/run-proxy-env.sh
  integration/run-ssh-env.sh
  internal/httpauth/client_test.go
  internal/ioutil/len_read_writer_test.go
  internal/noise/net.go
  internal/noise/net_test.go
  internal/noise/noise.go
  internal/noise/noise_test.go
  internal/therealproxy/server_test.go
  internal/therealssh/server.go
  internal/therealssh/server_test.go
  pkg/app/app_test.go
  pkg/cipher/cipher_test.go
  pkg/dmsg/client_test.go
  pkg/manager/node_test.go
  pkg/messaging-discovery/client/entry_test.go
  pkg/messaging/factory_test.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/router/router_test.go
  pkg/routing/routing_table_test.go
  pkg/setup/node_test.go
  pkg/transport-discovery/client/client_test.go
  pkg/transport/manager.go
  pkg/transport/manager_test.go
  vendor/github.com/pkg/profile/.travis.yml
  vendor/github.com/pkg/profile/AUTHORS
  vendor/github.com/pkg/profile/LICENSE
  vendor/github.com/pkg/profile/README.md
  vendor/github.com/pkg/profile/mutex.go
  vendor/github.com/pkg/profile/mutex17.go
  vendor/github.com/pkg/profile/profile.go
  vendor/github.com/pkg/profile/trace.go
  vendor/github.com/pkg/profile/trace16.go
  vendor/modules.txt
Labels: mainnet

#430 Bug: double definition of TestMain in dmsg
  pkg/dmsg/client_test.go
Labels: bug, mainnet

#440 Fix lingering transports after dmsg.Server disconnects.
  pkg/dmsg/client.go
  pkg/dmsg/server_test.go
Labels: bug, dmsg, mainnet

#414 Feature/apps retry on network error
  cmd/apps/skychat/chat.go
  cmd/apps/therealproxy-client/therealproxy-client.go
  go.mod
  go.sum
  internal/netutil/retrier.go
  internal/netutil/retrier_test.go
  internal/therealproxy/client.go
  internal/therealproxy/server.go
  internal/therealssh/client.go
  pkg/app/app.go
  vendor/github.com/alecthomas/template/LICENSE
  vendor/github.com/alecthomas/template/README.md
  vendor/github.com/alecthomas/template/doc.go
  vendor/github.com/alecthomas/template/exec.go
  vendor/github.com/alecthomas/template/funcs.go
  vendor/github.com/alecthomas/template/helper.go
  vendor/github.com/alecthomas/template/parse/lex.go
  vendor/github.com/alecthomas/template/parse/node.go
  vendor/github.com/alecthomas/template/parse/parse.go
  vendor/github.com/alecthomas/template/template.go
  vendor/github.com/alecthomas/units/COPYING
  vendor/github.com/alecthomas/units/README.md
  vendor/github.com/alecthomas/units/bytes.go
  vendor/github.com/alecthomas/units/doc.go
  vendor/github.com/alecthomas/units/si.go
  vendor/github.com/alecthomas/units/util.go
  vendor/github.com/prometheus/common/log/eventlog_formatter.go
  vendor/github.com/prometheus/common/log/log.go
  vendor/github.com/prometheus/common/log/syslog_formatter.go
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/mksyscall.go
  vendor/golang.org/x/sys/windows/registry/syscall.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/registry/zsyscall_windows.go
  vendor/golang.org/x/sys/windows/svc/eventlog/install.go
  vendor/golang.org/x/sys/windows/svc/eventlog/log.go
  vendor/gopkg.in/alecthomas/kingpin.v2/.travis.yml
  vendor/gopkg.in/alecthomas/kingpin.v2/COPYING
  vendor/gopkg.in/alecthomas/kingpin.v2/README.md
  vendor/gopkg.in/alecthomas/kingpin.v2/actions.go
  vendor/gopkg.in/alecthomas/kingpin.v2/app.go
  vendor/gopkg.in/alecthomas/kingpin.v2/args.go
  vendor/gopkg.in/alecthomas/kingpin.v2/cmd.go
  vendor/gopkg.in/alecthomas/kingpin.v2/completions.go
  vendor/gopkg.in/alecthomas/kingpin.v2/doc.go
  vendor/gopkg.in/alecthomas/kingpin.v2/envar.go
  vendor/gopkg.in/alecthomas/kingpin.v2/flags.go
  vendor/gopkg.in/alecthomas/kingpin.v2/global.go
  vendor/gopkg.in/alecthomas/kingpin.v2/guesswidth.go
  vendor/gopkg.in/alecthomas/kingpin.v2/guesswidth_unix.go
  vendor/gopkg.in/alecthomas/kingpin.v2/model.go
  vendor/gopkg.in/alecthomas/kingpin.v2/parser.go
  vendor/gopkg.in/alecthomas/kingpin.v2/parsers.go
  vendor/gopkg.in/alecthomas/kingpin.v2/templates.go
  vendor/gopkg.in/alecthomas/kingpin.v2/usage.go
  vendor/gopkg.in/alecthomas/kingpin.v2/values.go
  vendor/gopkg.in/alecthomas/kingpin.v2/values.json
  vendor/gopkg.in/alecthomas/kingpin.v2/values_generated.go
  vendor/modules.txt
Labels: mainnet

#450 Fix rare 'panic: send on closed channel' with dmsg.Transport
  go.mod
  go.sum
  pkg/dmsg/transport.go
  vendor/golang.org/x/sys/unix/dirent.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_netbsd.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/modules.txt
Labels: bug, dmsg, mainnet
