Repository skycoin/skywire, pull requests merged in 2019-07, with the labels that each got.

#465 Fixed some routing logic.
  cmd/apps/skychat/chat.go
  integration/test-messaging.sh
  pkg/app/app.go
  pkg/node/rpc.go
  pkg/node/rpc_test.go
  pkg/router/router.go
  pkg/router/router_test.go
  pkg/setup/node_test.go
  pkg/transport/log.go
  pkg/transport/log_test.go
  pkg/transport/managed_transport.go
  pkg/transport/manager.go
  pkg/transport/manager_test.go
Labels: enhancement, mainnet

#472 added dockerfiles
  .dockerignore
  docker/images/node/Dockerfile
  docker/images/node/update.sh
Labels: mainnet

#476 Feature/add cli to node
  docker/images/node/Dockerfile
Labels: enhancement, mainnet

#490 Fix various panics.
  go.mod
  go.sum
  pkg/app/app.go
  pkg/transport/manager.go
  vendor/github.com/skycoin/dmsg/.golangci.yml
  vendor/github.com/skycoin/dmsg/README.md
  vendor/github.com/skycoin/dmsg/client.go
  vendor/github.com/skycoin/dmsg/disc/client.go
  vendor/github.com/skycoin/dmsg/disc/entry.go
  vendor/github.com/skycoin/dmsg/ioutil/ack_waiter.go
  vendor/github.com/skycoin/dmsg/ioutil/buf_read.go
  vendor/github.com/skycoin/dmsg/ioutil/logging.go
  vendor/github.com/skycoin/dmsg/noise/noise.go
  vendor/github.com/skycoin/dmsg/server.go
  vendor/github.com/skycoin/dmsg/transport.go
  vendor/golang.org/x/net/nettest/conntest.go
  vendor/golang.org/x/net/nettest/nettest.go
  vendor/golang.org/x/net/nettest/nettest_stub.go
  vendor/golang.org/x/net/nettest/nettest_unix.go
  vendor/golang.org/x/net/nettest/nettest_windows.go
  vendor/modules.txt
Labels: bug, mainnet
