Repository skycoin/skywire, pull requests merged in 2019-08, with the labels that each got.

#510 Added pty flags to ssh CLI
  cmd/therealssh-cli/commands/root.go
  pkg/therealssh/pty_test.go
Labels: enhancement

#511 [BUG] added resilience for unix socket dial
  cmd/therealssh-cli/commands/root.go
  pkg/therealssh/pty_test.go
Labels: bug, mainnet

#508 [WIP] Decouple managedTransport and improve transport handling logic.
  pkg/route-finder/client/mock.go
  pkg/router/app_manager.go
  pkg/router/app_manager_test.go
  pkg/router/route_manager.go
  pkg/router/route_manager_test.go
  pkg/router/router.go
  pkg/router/router_test.go
  pkg/routing/packet.go
  pkg/routing/rule.go
  pkg/setup/config.go
  pkg/setup/node.go
  pkg/setup/node_test.go
  pkg/setup/protocol.go
  pkg/transport-discovery/client/client_test.go
  pkg/transport/dmsg/testing.go
  pkg/transport/entry.go
  pkg/transport/entry_test.go
  pkg/transport/handshake.go
  pkg/transport/handshake_test.go
  pkg/transport/managed_transport.go
  pkg/transport/manager.go
  pkg/transport/manager_test.go
  pkg/transport/mock.go
  pkg/transport/transport.go
  pkg/visor/rpc.go
  pkg/visor/rpc_client.go
  pkg/visor/rpc_test.go
  pkg/visor/visor.go
  pkg/visor/visor_test.go
  vendor/modules.txt
Labels: bug, enhancement, mainnet

#523 Fix router tests.
  go.mod
  go.sum
  internal/testhelpers/testhelpers.go
  pkg/app/app.go
  pkg/app/app_test.go
  pkg/router/app_manager.go
  pkg/router/app_manager_test.go
  pkg/router/route_manager.go
  pkg/router/router.go
  pkg/router/router_test.go
  pkg/snet/network.go
  pkg/snet/snettest/env.go
  pkg/therealssh/channel_test.go
  pkg/transport/handshake_test.go
  pkg/transport/manager.go
  pkg/transport/manager_test.go
  pkg/transport/mock.go
  pkg/visor/visor_test.go
  vendor/github.com/skycoin/dmsg/listener.go
  vendor/github.com/skycoin/dmsg/transport.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_darwin_386.go
  vendor/golang.org/x/sys/unix/syscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/syscall_darwin_arm.go
  vendor/golang.org/x/sys/unix/syscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_386.1_11.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_386.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_386.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/modules.txt
Labels: mainnet
