Repository skycoin/skywire, pull requests merged in 2019-03, with the labels that each got.

#212 Bug/fix logstore dir
  Makefile
  go.mod
  go.sum
  pkg/node/config.go
  pkg/node/config_test.go
  pkg/node/node.go
  pkg/transport/log.go
  pkg/transport/log_test.go
  vendor/modules.txt
Labels: bug, mainnet

#206 [WIP] re-connect logic for server connections in messaging-client
  cmd/skywire-cli/commands/config.go
  pkg/messaging/chan_list.go
  pkg/messaging/channel.go
  pkg/messaging/client.go
  pkg/messaging/client_test.go
  pkg/node/config.go
  pkg/node/config_test.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/router/route_manager.go
Labels: bug, mainnet

#220 Thread-safe rule
  pkg/router/route_manager.go
Labels: bug, mainnet

#240 Made corrections Makefile and travis to conform skycoin standards
  .travis.yml
  Makefile
  README.md
Labels: mainnet

#239 Add user management to manager node.
  cmd/manager-node/commands/init-config.go
  cmd/manager-node/commands/root.go
  go.mod
  go.sum
  internal/pathutil/homedir.go
  pkg/manager/config.go
  pkg/manager/node.go
  pkg/manager/node_test.go
  pkg/manager/user.go
  pkg/manager/user_manager.go
  pkg/routing/boltdb_routing_table.go
  vendor/github.com/gorilla/securecookie/.travis.yml
  vendor/github.com/gorilla/securecookie/LICENSE
  vendor/github.com/gorilla/securecookie/README.md
  vendor/github.com/gorilla/securecookie/doc.go
  vendor/github.com/gorilla/securecookie/fuzz.go
  vendor/github.com/gorilla/securecookie/securecookie.go
  vendor/modules.txt
Labels: mainnet

#208 Added multiple paths for config.
  cmd/skywire-cli/commands/config.go
  cmd/skywire-node/commands/root.go
  internal/pathutil/data.go
Labels: enhancement, in progress, mainnet
